second file has to be run w/ python3
